import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/Layout/Navbar";
import Footer from "@/Layout/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Prashant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="geistMono.className">
      <body className={`font-mono ${geistSans.variable} ${geistMono.variable} antialiased min-h-screen p-1  flex flex-col`}>
        <Navbar />
        <main className="flex-grow">
          <div className="container mx-auto flex justify-center items-center px-4 sm:px-6 h-[83vh] overflow-auto lg:px-8">
            {children}
          </div>
        </main>
        <Footer />
      </body>

    </html>
  );
}
